# Generated by Django 3.0.4 on 2020-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20200416_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_validity',
            field=models.DateField(),
        ),
    ]
