# Generated by Django 3.0.5 on 2020-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_auto_20200417_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_pubdate',
            field=models.DateTimeField(),
        ),
    ]
